// headCells.js
export const headCells = [
  {
    id: "name", // this id should be same as the key of the object in tableData.js
    numeric: false,
    disablePadding: true,
    label: "Dessert (100g serving)",
  },
  {
    id: "calories",
    numeric: true,
    disablePadding: false,
    label: "Calories",
  },
  {
    id: "fat",
    numeric: true,
    disablePadding: false,
    label: "Fat (g)",
  },
  {
    id: "carbs",
    numeric: true,
    disablePadding: false,
    label: "Carbs (g)",
  },
  {
    id: "protein",
    numeric: true,
    disablePadding: false,
    label: "Protein (g)",
  },
  {
    id: "category",
    numeric: false,
    disablePadding: false,
    label: "Category",
  },
  {
    id: "color",
    numeric: false,
    disablePadding: false,
    label: "Color",
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Status",
  },
  {
    id: "payment",
    numeric: false,
    disablePadding: false,
    label: "Payment",
  },
  {
    id: "actions",
    numeric: false,
    disablePadding: false,
    label: "Actions",
  },
];


// these are filter box options
export const filterOptions = [
  {
    id:'category', // this id should be same as the id in headCells.js
    label: "Category",
    options: ["Electronics", "Clothing"],
  },
  {
    id:'color',
    label: "Color",
    options: ["Green", "Yello"],
  },
  {
    id:'status',
    label: "Status",
    options: ["Active", "Disable"],
  },
  {
    id:'payment',
    label: "Payment",
    options: ["Paid", "Unpaid"],
  },
];


// tableData.js
export const tableData = [
    {
      id: 1,
      name: "Cupcake",
      calories: 305,
      fat: 3.7,
      carbs: 67,
      protein: 4.3,
      category: "Clothing",
      color: "Green",
      status: "Active",
      payment: "Paid",
    },
    {
      id: 2,
      name: "Donut",
      calories: 452,
      fat: 25.0,
      carbs: 51,
      protein: 4.9,
      category: "Electronics",
      color: "Yellow",
      status: "Disabled",
      payment: "Unpaid",
    },
    {
      id: 3,
      name: "Eclair",
      calories: 262,
      fat: 16.0,
      carbs: 24,
      protein: 6.0,
      category: "Clothing",
      color: "Green",
      status: "Active",
      payment: "Paid",
    },
    {
      id: 4,
      name: "Frozen yoghurt",
      calories: 159,
      fat: 6.0,
      carbs: 24,
      protein: 4.0,
      category: "Electronics",
      color: "Green",
      status: "Disabled",
      payment: "Paid",
    },
    {
      id: 5,
      name: "Gingerbread",
      calories: 356,
      fat: 16.0,
      carbs: 49,
      protein: 3.9,
      category: "Clothing",
      color: "Yellow",
      status: "Active",
      payment: "Unpaid",
    },
    {
      id: 6,
      name: "Honeycomb",
      calories: 408,
      fat: 3.2,
      carbs: 87,
      protein: 6.5,
      category: "Electronics",
      color: "Green",
      status: "Disabled",
      payment: "Paid",
    },
    {
      id: 7,
      name: "Ice cream sandwich",
      calories: 237,
      fat: 9.0,
      carbs: 37,
      protein: 4.3,
      category: "Clothing",
      color: "Yellow",
      status: "Active",
      payment: "Unpaid",
    },
    {
      id: 8,
      name: "Jelly Bean",
      calories: 375,
      fat: 0.0,
      carbs: 94,
      protein: 0.0,
      category: "Electronics",
      color: "Yellow",
      status: "Disabled",
      payment: "Paid",
    },
    {
      id: 9,
      name: "KitKat",
      calories: 518,
      fat: 26.0,
      carbs: 65,
      protein: 7.0,
      category: "Clothing",
      color: "Green",
      status: "Active",
      payment: "Unpaid",
    },
    {
      id: 10,
      name: "Lollipop",
      calories: 392,
      fat: 0.2,
      carbs: 98,
      protein: 0.0,
      category: "Electronics",
      color: "Yellow",
      status: "Disabled",
      payment: "Paid",
    },
    {
      id: 11,
      name: "Marshmallow",
      calories: 318,
      fat: 0,
      carbs: 81,
      protein: 2.0,
      category: "Clothing",
      color: "Green",
      status: "Active",
      payment: "Unpaid",
    },
    {
      id: 12,
      name: "Nougat",
      calories: 360,
      fat: 19.0,
      carbs: 9,
      protein: 37.0,
      category: "Electronics",
      color: "Green",
      status: "Disabled",
      payment: "Paid",
    },
    {
      id: 13,
      name: "Oreo",
      calories: 437,
      fat: 18.0,
      carbs: 63,
      protein: 4.0,
      category: "Clothing",
      color: "Yellow",
      status: "Active",
      payment: "Unpaid",
    },
  ];
  