import image1 from '../../../assets/images/products/tshirt.jpg'
import image2 from '../../../assets/images/products/denim.jpg'
import image3 from '../../../assets/images/products/Shoes.jpg'
import image4 from '../../../assets/images/products/scarf.jpg'
import image5 from '../../../assets/images/products/leather jacket.jpg'
import image6 from '../../../assets/images/products/Casual Shirt.jpg'
import image7 from '../../../assets/images/products/Rings.jpg'
import image8 from '../../../assets/images/products/shirt.jpg'
import image9 from '../../../assets/images/products/yoga pants.jpg'
import image10 from '../../../assets/images/products/backpack.jpg'
import image11 from '../../../assets/images/products/sunglasses.jpg'
import image12 from '../../../assets/images/products/perfume.jpg'
import WebApi from '../../../api/WebApi'


export const fetchData = async () => {
  try {

    const response = await WebApi.get(`/shop/order/getOrderByShopId/${localStorage.getItem('id')}`);
    console.log(response.data)
    return response.data;

  } catch (error) {
    console.log(error)
  }
}

export const changeStatus = async (orderItemId, status) => {
  try{
    const response = await WebApi.get(`/shop/order/changeStatusByOrderItemId/${orderItemId}/${status}`)
    console.log(response.data)
  }catch(error){
    console.log(error)
  }
}


// headCells.js
export const headCellsRecentOrders = [
  {
    id: "info", // this id should be same as the key of the object in tableData.js
    numeric: false,
    disablePadding: true,
    label: "PRODUCT INFO",
  },
  {
    id: "imageURL",
    numeric: false,
    disablePadding: true,
  },
  // {
  //   id: "customer",
  //   numeric: false,
  //   disablePadding: false,
  //    label: "CUSTOMER",
  // },
  {
    id: "customerName",
    numeric: true,
    disablePadding: false,
    label: "PRODUCT NAME",
  },
  {
    id: "quantity",
    numeric: false,
    disablePadding: false,
    label: "QUANTITY",
  },
  {
    id: "price",
    numeric: true,
    disablePadding: false,
    label: "TOTAL AMOUNT(Rs.)",
  },
  {
    id: "ordered_date",
    numeric: false,
    disablePadding: false,
    label: "ORDERED DATE",
  },
  {
    id: "actions",
    numeric: false,
    disablePadding: false,
    label: "Actions",
  },
];

export const headCellsAcceptedOrders = [
  {
    id: "info", // this id should be same as the key of the object in tableData.js
    numeric: false,
    disablePadding: true,
    label: "PRODUCT INFO",
  },
  {
    id: "imageUrl",
    numeric: false,
    disablePadding: true,
  },
  // {
  //   id: "courier",
  //   numeric: true,
  //   disablePadding: false,
  //   label: "COURIER",
  // },
  {
    id: "customerName",
    numeric: true,
    disablePadding: false,
    label: "COURIER",
  },
  {
    id: "quantity",
    numeric: false,
    disablePadding: false,
    label: "QUANTITY",
  },
  {
    id: "price",
    numeric: true,
    disablePadding: false,
    label: "TOTAL AMOUNT(Rs.)",
  },
  {
    id: "ordered_date",
    numeric: false,
    disablePadding: false,
    label: "ORDERED DATE",
  },
  {
    id: "orderStatus",
    numeric: false,
    disablePadding: false,
    label: "STATUS",
    disableSort: true,
  },
];

export const headCellsRejectedOrders = [
  {
    id: "info", // this id should be same as the key of the object in tableData.js
    numeric: false,
    disablePadding: true,
    label: "PRODUCT INFO",
  },
  {
    id: "imageUrl",
    numeric: false,
    disablePadding: true,
  },
  // {
  //   id: "courier",
  //   numeric: true,
  //   disablePadding: false,
  //   label: "COURIER",
  // },
  {
    id: "customerName",
    numeric: true,
    disablePadding: false,
    label: "COURIER",
  },
  {
    id: "quantity",
    numeric: false,
    disablePadding: false,
    label: "QUANTITY",
  },
  {
    id: "price",
    numeric: true,
    disablePadding: false,
    label: "TOTAL AMOUNT(Rs.)",
  },
  {
    id: "ordered_date",
    numeric: false,
    disablePadding: false,
    label: "ORDERED DATE",
  },
  {
    id: "orderStatus",
    numeric: false,
    disablePadding: false,
    label: "STATUS",
    disableSort: true,
  },
];

export const additionalFields = [

  {
    id: "cardNo",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "phone",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "storeName",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "payment_method",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "deliveryDate",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "unit_price",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "size",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "category",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "address",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "customerEmail",
    numeric: true,
    disablePadding: false,
  },
  {
    id: "customerPhone",
    numeric: true,
    disablePadding: false,
  },

];

// these are filter box options
export const filterOptions = [
  {
    id: "price",
    label: "Price",
    options: ["Below 5000", "Below 10000", "Below 15000"]
  },
  {
    id: "ordered_date",
    label: "Order Date",
    options: ["Today", "Last Seven Days", "Last Thirty Days"]
  },
];


// tableData.js
export const tableData = [
  {
    id: 1,
    info: "Casual T-Shirts",
    orderId: "081794MT",
    customerName: "Priya",
    courier: "FedEx",
    quantity: 2,
    price: 4000,
    ordered_date: "2024-07-10",
    brand: "Bear Appeal",
    category: "Tops",
    subcategory: "T-shirts",
    color: "White",
    size: "M",
    unit_price: 2000,
    customerEmail: "priya@example.com",
    customerPhone: "9876543210",
    deliveryDate: "2024-07-12",
    address: "123 Main St, Chennai",
    cardNo: "1234567890123456",
    storeName: "ArunStyles",
    phone: "9876543210",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image1,
  },
  {
    id: 2,
    info: "Slim Fit Jeans",
    orderId: "081794MT",
    customerName: "Ruhina",
    courier: "Domex",
    quantity: 1,
    price: 4000,
    ordered_date: "2024-07-11",
    brand: "Levi's",
    category: "Bottoms",
    subcategory: "Jeans",
    color: "Blue",
    size: "L",
    unit_price: 4000,
    customerEmail: "ruhina@example.com",
    customerPhone: "9876543211",
    deliveryDate: "2024-07-13",
    address: "456 Elm St, Mumbai",
    cardNo: "1234567890123457",
    storeName: "ArunStyles",
    phone: "9876543211",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image2,
  },
  {
    id: 3,
    info: "Running Shoes",
    orderId: "081794MT",
    customerName: "Arshidha",
    courier: "Pronto Lanka",
    quantity: 1,
    price: 11000,
    ordered_date: "2024-07-12",
    brand: "Nike",
    category: "Footwear",
    subcategory: "Shoes",
    color: "Undefined",
    size: "9",
    unit_price: 11000,
    customerEmail: "arshidha@example.com",
    customerPhone: "9876543212",
    deliveryDate: "2024-07-14",
    address: "789 Pine St, Bangalore",
    cardNo: "1234567890123458",
    storeName: "ArunStyles",
    phone: "9876543212",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image3,
  },
  {
    id: 4,
    info: "Woolen Scarf",
    orderId: "081794MT",
    customerName: "Naveena",
    courier: "FedEx",
    quantity: 2,
    price: 7000,
    ordered_date: "2024-07-13",
    brand: "Cashmere",
    category: "Accessories",
    subcategory: "Scarves",
    color: "Brown",
    size: "One Size",
    unit_price: 3500,
    customerEmail: "naveena@example.com",
    customerPhone: "9876543213",
    deliveryDate: "2024-07-15",
    address: "101 Maple St, Delhi",
    cardNo: "1234567890123459",
    storeName: "ArunStyles",
    phone: "9876543213",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image4,
  },
  {
    id: 5,
    info: "Leather Jacket",
    orderId: "081794MT",
    customerName: "Krishtika",
    courier: "Domex",
    quantity: 1,
    price: 8320,
    ordered_date: "2024-07-14",
    brand: "AllSaints",
    category: "Outer Wear",
    subcategory: "Jackets",
    color: "Black",
    size: "XL",
    unit_price: 8320,
    customerEmail: "krishtika@example.com",
    customerPhone: "9876543214",
    deliveryDate: "2024-07-16",
    address: "202 Oak St, Pune",
    cardNo: "1234567890123460",
    storeName: "ArunStyles",
    phone: "9876543214",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image5,
  },
  {
    id: 6,
    info: "Casual Shirt",
    orderId: "081794MT",
    customerName: "Ashwin",
    courier: "Pronto Lanka",
    quantity: 3,
    price: 9750,
    ordered_date: "2024-07-15",
    brand: "Tommy Hilfiger",
    category: "Tops",
    subcategory: "Shirts",
    color: "Black",
    size: "L",
    unit_price: 3250,
    customerEmail: "ashwin@example.com",
    customerPhone: "9876543215",
    deliveryDate: "2024-07-17",
    address: "303 Birch St, Kolkata",
    cardNo: "1234567890123461",
    storeName: "ArunStyles",
    phone: "9876543215",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image6,
  },
  {
    id: 7,
    info: "Rings",
    orderId: "081794MT",
    customerName: "Aashif",
    courier: "Domex",
    quantity: 2,
    price: 3500,
    ordered_date: "2024-07-16",
    brand: "No Brand",
    category: "Jewelry",
    subcategory: "Rings",
    color: "Undefined",
    size: "One Size",
    unit_price: 1750,
    customerEmail: "aashif@example.com",
    customerPhone: "9876543216",
    deliveryDate: "2024-07-18",
    address: "404 Cedar St, Hyderabad",
    cardNo: "1234567890123462",
    storeName: "ArunStyles",
    phone: "9876543216",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image7,
  },
  {
    id: 8,
    info: "Formal Shirt",
    orderId: "081794MT",
    customerName: "Hijas",
    courier: "Pronto Lanka",
    quantity: 4,
    price: 12000,
    ordered_date: "2024-07-17",
    brand: "SWX",
    category: "Tops",
    subcategory: "Shirts",
    color: "White",
    size: "M",
    unit_price: 3000,
    customerEmail: "hijas@example.com",
    customerPhone: "9876543217",
    deliveryDate: "2024-07-19",
    address: "505 Maple St, Chennai",
    cardNo: "1234567890123463",
    storeName: "ArunStyles",
    phone: "9876543217",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image8,
  },
  {
    id: 9,
    info: "Yoga Pants",
    orderId: "081794MT",
    customerName: "Pranavi",
    courier: "FedEx",
    quantity: 2,
    price: 10000,
    ordered_date: "2024-07-18",
    brand: "Lululemon",
    category: "Bottoms",
    subcategory: "Active Wear",
    color: "Green",
    size: "S",
    unit_price: 5000,
    customerEmail: "pranavi@example.com",
    customerPhone: "9876543218",
    deliveryDate: "2024-07-20",
    address: "606 Oak St, Bangalore",
    cardNo: "1234567890123464",
    storeName: "ArunStyles",
    phone: "9876543218",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image9,
  },
  {
    id: 10,
    info: "Backpack",
    orderId: "081794MT",
    customerName: "Dinesh",
    courier: "Domex",
    quantity: 1,
    price: 6500,
    ordered_date: "2024-07-19",
    brand: "Jansport",
    category: "Accessories",
    subcategory: "Bag",
    color: "Blue",
    size: "One Size",
    unit_price: 6500,
    customerEmail: "dinesh@example.com",
    customerPhone: "9876543219",
    deliveryDate: "2024-07-21",
    address: "707 Elm St, Mumbai",
    cardNo: "1234567890123465",
    storeName: "ArunStyles",
    phone: "9876543219",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image10,
  },
  {
    id: 11,
    info: "Sunglasses",
    orderId: "081794MT",
    customerName: "Sudarshan",
    courier: "Pronto Lanka",
    quantity: 1,
    price: 2500,
    ordered_date: "2024-07-20",
    brand: "Lenskart",
    category: "Accessories",
    subcategory: "Glasses",
    color: "Black",
    size: "One Size",
    unit_price: 2500,
    customerEmail: "sudarshan@example.com",
    customerPhone: "9876543220",
    deliveryDate: "2024-07-22",
    address: "808 Pine St, Pune",
    cardNo: "1234567890123466",
    storeName: "ArunStyles",
    phone: "9876543220",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image11,
  },
  {
    id: 12,
    info: "Perfume",
    orderId: "081794MT",
    customerName: "Dhanushika",
    courier: "FedEx",
    quantity: 2,
    price: 5000,
    ordered_date: "2024-07-21",
    brand: "Givenchy",
    category: "Accessories",
    subcategory: "Fragrance",
    color: "Undefined",
    size: "One Size",
    unit_price: 2500,
    customerEmail: "dhanushika@example.com",
    customerPhone: "9876543221",
    deliveryDate: "2024-07-23",
    address: "909 Birch St, Delhi",
    cardNo: "1234567890123467",
    storeName: "ArunStyles",
    phone: "9876543221",
    payment_method: "Credit Card",
    orderStatus: "Recent",
    imageUrl: image12,
  }
];

export const acceptedOrders = [
  {
    id: 1,
    info: "Casual T-Shirts",
    orderId: "081794MT",
    customerName: "Priya",
    courier: "FedEx",
    quantity: 2,
    price: 4000,
    ordered_date: "2024-07-10",
    brand: "Bear Appeal",
    category: "Tops",
    subcategory: "T-shirts",
    color: "White",
    size: "M",
    unit_price: 2000,
    customerEmail: "priya@example.com",
    customerPhone: "9876543210",
    deliveryDate: "2024-07-12",
    address: "123 Main St, Chennai",
    cardNo: "1234567890123456",
    storeName: "ArunStyles",
    phone: "9876543210",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image1,
  },
  {
    id: 2,
    info: "Slim Fit Jeans",
    orderId: "081794MT",
    customerName: "Ruhina",
    courier: "Domex",
    quantity: 1,
    price: 4000,
    ordered_date: "2024-07-11",
    brand: "Levi's",
    category: "Bottoms",
    subcategory: "Jeans",
    color: "Blue",
    size: "L",
    unit_price: 4000,
    customerEmail: "ruhina@example.com",
    customerPhone: "9876543211",
    deliveryDate: "2024-07-13",
    address: "456 Elm St, Mumbai",
    cardNo: "1234567890123457",
    storeName: "ArunStyles",
    phone: "9876543211",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image2,
  },
  {
    id: 3,
    info: "Running Shoes",
    orderId: "081794MT",
    customerName: "Arshidha",
    courier: "Pronto Lanka",
    quantity: 1,
    price: 11000,
    ordered_date: "2024-07-12",
    brand: "Nike",
    category: "Footwear",
    subcategory: "Shoes",
    color: "Undefined",
    size: "9",
    unit_price: 11000,
    customerEmail: "arshidha@example.com",
    customerPhone: "9876543212",
    deliveryDate: "2024-07-14",
    address: "789 Pine St, Bangalore",
    cardNo: "1234567890123458",
    storeName: "ArunStyles",
    phone: "9876543212",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image3,
  },
  {
    id: 4,
    info: "Woolen Scarf",
    orderId: "081794MT",
    customerName: "Naveena",
    courier: "FedEx",
    quantity: 2,
    price: 7000,
    ordered_date: "2024-07-13",
    brand: "Cashmere",
    category: "Accessories",
    subcategory: "Scarves",
    color: "Brown",
    size: "One Size",
    unit_price: 3500,
    customerEmail: "naveena@example.com",
    customerPhone: "9876543213",
    deliveryDate: "2024-07-15",
    address: "101 Maple St, Delhi",
    cardNo: "1234567890123459",
    storeName: "ArunStyles",
    phone: "9876543213",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image4,
  },
  {
    id: 5,
    info: "Leather Jacket",
    orderId: "081794MT",
    customerName: "Krishtika",
    courier: "Domex",
    quantity: 1,
    price: 8320,
    ordered_date: "2024-07-14",
    brand: "AllSaints",
    category: "Outer Wear",
    subcategory: "Jackets",
    color: "Black",
    size: "XL",
    unit_price: 8320,
    customerEmail: "krishtika@example.com",
    customerPhone: "9876543214",
    deliveryDate: "2024-07-16",
    address: "202 Oak St, Pune",
    cardNo: "1234567890123460",
    storeName: "ArunStyles",
    phone: "9876543214",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image5,
  },
  {
    id: 6,
    info: "Casual Shirt",
    orderId: "081794MT",
    customerName: "Ashwin",
    courier: "Pronto Lanka",
    quantity: 3,
    price: 9750,
    ordered_date: "2024-07-15",
    brand: "Tommy Hilfiger",
    category: "Tops",
    subcategory: "Shirts",
    color: "Black",
    size: "L",
    unit_price: 3250,
    customerEmail: "ashwin@example.com",
    customerPhone: "9876543215",
    deliveryDate: "2024-07-17",
    address: "303 Birch St, Kolkata",
    cardNo: "1234567890123461",
    storeName: "ArunStyles",
    phone: "9876543215",
    payment_method: "Credit Card",
    orderStatus: "Accepted",
    imageUrl: image6,
  },
];

export const rejectedOrders = [
  {
    id: 1,
    info: "Baseball Cap",
    orderId: "081794MT",
    customerName: "Aashif",
    courier: "Domex",
    quantity: 2,
    price: 3500,
    ordered_date: "2024-07-16",
    brand: "Sporty Gear",
    category: "Accessories",
    subcategory: "Hats",
    color: "Undefined",
    size: "One Size",
    unit_price: 1750,
    customerEmail: "aashif@example.com",
    customerPhone: "9876543216",
    deliveryDate: "2024-07-18",
    address: "404 Cedar St, Hyderabad",
    cardNo: "1234567890123462",
    storeName: "ArunStyles",
    phone: "9876543216",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image7,
  },
  {
    id: 2,
    info: "Formal Shirt",
    orderId: "081794MT",
    customerName: "Hijas",
    courier: "Pronto Lanka",
    quantity: 4,
    price: 12000,
    ordered_date: "2024-07-17",
    brand: "SWX",
    category: "Tops",
    subcategory: "Shirts",
    color: "Blue",
    size: "M",
    unit_price: 3000,
    customerEmail: "hijas@example.com",
    customerPhone: "9876543217",
    deliveryDate: "2024-07-19",
    address: "505 Maple St, Chennai",
    cardNo: "1234567890123463",
    storeName: "ArunStyles",
    phone: "9876543217",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image8,
  },
  {
    id: 3,
    info: "Yoga Pants",
    orderId: "081794MT",
    customerName: "Pranavi",
    courier: "FedEx",
    quantity: 2,
    price: 10000,
    ordered_date: "2024-07-18",
    brand: "Lululemon",
    category: "Bottoms",
    subcategory: "Active Wear",
    color: "Purple",
    size: "S",
    unit_price: 5000,
    customerEmail: "pranavi@example.com",
    customerPhone: "9876543218",
    deliveryDate: "2024-07-20",
    address: "606 Oak St, Bangalore",
    cardNo: "1234567890123464",
    storeName: "ArunStyles",
    phone: "9876543218",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image9,
  },
  {
    id: 4,
    info: "Backpack",
    orderId: "081794MT",
    customerName: "Dinesh",
    courier: "Domex",
    quantity: 1,
    price: 6500,
    ordered_date: "2024-07-19",
    brand: "Jansport",
    category: "Accessories",
    subcategory: "Bag",
    color: "Undefined",
    size: "One Size",
    unit_price: 6500,
    customerEmail: "dinesh@example.com",
    customerPhone: "9876543219",
    deliveryDate: "2024-07-21",
    address: "707 Elm St, Mumbai",
    cardNo: "1234567890123465",
    storeName: "ArunStyles",
    phone: "9876543219",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image10,
  },
  {
    id: 5,
    info: "Sunglasses",
    orderId: "081794MT",
    customerName: "Sudarshan",
    courier: "Pronto Lanka",
    quantity: 1,
    price: 2500,
    ordered_date: "2024-07-20",
    brand: "Lenskart",
    category: "Accessories",
    subcategory: "Glasses",
    color: "Undefined",
    size: "One Size",
    unit_price: 2500,
    customerEmail: "sudarshan@example.com",
    customerPhone: "9876543220",
    deliveryDate: "2024-07-22",
    address: "808 Pine St, Pune",
    cardNo: "1234567890123466",
    storeName: "ArunStyles",
    phone: "9876543220",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image11,
  },
  {
    id: 6,
    info: "Perfume",
    orderId: "081794MT",
    customerName: "Dhanushika",
    courier: "FedEx",
    quantity: 2,
    price: 5000,
    ordered_date: "2024-07-21",
    brand: "Givenchy",
    category: "Accessories",
    subcategory: "Fragrance",
    color: "Undefined",
    size: "One Size",
    unit_price: 2500,
    customerEmail: "dhanushika@example.com",
    customerPhone: "9876543221",
    deliveryDate: "2024-07-23",
    address: "909 Birch St, Delhi",
    cardNo: "1234567890123467",
    storeName: "ArunStyles",
    phone: "9876543221",
    payment_method: "Credit Card",
    orderStatus: "Rejected",
    imageUrl: image12,
  }
];

