export const Colors = {
  colors : [
    {
      name: "Black",
      hexCode: "#000000",
    },
    {
      name: "White",
      hexCode: "#FFFFFF",
    },
    {
      name: "Gray",
      hexCode: "#BDBDBD",
    },
    {
      name: "Red",
      hexCode: "#D21B28",
    },
    {
      name: "Pink",
      hexCode: "#FFB6B6",
    },
    {
      name: "Orange",
      hexCode: "#FFBA09",
    },
    {
      name: "Yellow",
      hexCode: "#FFF72E",
    },
    {
      name: "Green",
      hexCode: "#4ECB71",
    },
    {
      name: "Blue",
      hexCode: "#6CB4EE",
    },
    {
      name: "Purple",
      hexCode: "#A669B0",
    },
    {
      name: "Brown",
      hexCode: "#C0A888",
    },
    {
      name: "Beige",
      hexCode: "#F8E8DC",
    },
    {
      name: "Multicolor",
      hexCode: "linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)",
    },
    {
      name: "B&W",
      hexCode: "repeating-linear-gradient(45deg, #000, #000 10px, #fff 10px, #fff 20px)",
    },
  ]
};

const ProductCategory = {
  women: {
    categories: {
      Tops: [
        "Short Sleeve T-Shirts",
        "Long Sleeve T-Shirts",
        "Shirts",
        "Tank Tops",
        "Off-the-Shoulder Tops",
        "High-Neck Blouses",
        "Wrap Blouses",
        "Crop Tops",
        "Blouson Tops",
        "Peplum Tops",
      ],
      Bottoms: [
        "Jeans",
        "A-line Skirts",
        "Pencil Skirts",
        "Leggings",
        "Joggers",
        "Shorts",
        "Denim Shorts",
        "Dress Trousers",
        "Culottes",
        "Palazzo Pants",
      ],
      Dresses: [
        "Maxi Dresses",
        "Midi Dresses",
        "Mini Dresses",
        "Bodycon Dresses",
        "A-line Dresses",
        "Wrap Dresses",
        "Shift Dresses",
      ],
      Outerwear: [
        "Jackets",
        "Coats",
        "Blazers",
        "Cardigans",
        "Parkas",
        "Bomber Jackets",
        "Trench Coats",
        "Puffer Jackets",
      ],
      Suits: [
        "Two-Piece Suits",
        "Jumpsuits",
        "Blazer & Skirt Suits",
        "Blazer & Trouser Suits",
      ],
      Footwear: [
        "Sneakers",
        "Sandals",
        "Heels",
        "Ankle Boots",
        "Loafers",
        "Pumps",
        "Ballet Flats",
        "Espadrilles",
        "Wedges",
      ],
      Bags: [
        "Handbags",
        "Tote Bags",
        "Backpacks",
        "Crossbody Bags",
        "Envelope Bags",
        "Clutches",
        "Sling Bags",
      ],
      Accessories: [
        "Belts",
        "Hats",
        "Scarves",
        "Sunglasses",
        "Gloves",
        "Watches",
        "Jewelry",
        "Hair Accessories",
      ],
      Lingerie: [
        "Bras",
        "Panties",
        "Bodysuits",
        "Lingerie Sets",
        "Shapewear",
        "Camisoles",
        "Nightgowns",
      ],
    },
  },
  men: {
    categories: {
      Tops: [
        "Short Sleeve T-Shirts",
        "Long Sleeve T-Shirts",
        "Polo Shirts",
        "Shirts",
        "Henley Shirts",
        "Sweatshirts",
        "Hoodies",
        "Tank Tops",
      ],
      Bottoms: [
        "Slim-fit Jeans",
        "Shorts",
        "Denim Shorts",
        "Denim Jeans",
        "Dress Trousers",
        "Joggers",
        "Chinos",
        "Cargo Pants",
      ],
      Suits: [
        "Two-Piece Suits",
        "Three-Piece Suits",
        "Tuxedos",
        "Blazer & Trouser Suits",
        "Vest & Trouser Suits",
      ],
      Outerwear: [
        "Jackets",
        "Coats",
        "Blazers",
        "Puffer Jackets",
        "Bomber Jackets",
        "Trench Coats",
        "Parkas",
      ],
      Footwear: [
        "Sneakers",
        "Slip-on Shoes",
        "Canvas Shoes",
        "Boots",
        "Loafers",
        "Oxfords",
        "Derbies",
        "Monk Straps",
      ],
      Bags: [
        "Backpacks",
        "Messenger Bags",
        "Briefcases",
        "Crossbody Bags",
        "Belt Bags",
        "Duffel Bags",
        "Laptop Bags",
      ],
      Accessories: [
        "Belts",
        "Hats",
        "Scarves",
        "Sunglasses",
        "Gloves",
        "Watches",
        "Ties",
        "Cufflinks",
      ],
      Underwear: [
        "Boxers",
        "Briefs",
        "Boxer Briefs",
        "Undershirts",
        "Socks",
        "Thermal Wear",
      ],
    },
  },
};

export default ProductCategory;
