import image1 from '../../assets/images/products/tshirt.jpg'
import image2 from '../../assets/images/products/denim.jpg'
import image3 from '../../assets/images/products/Shoes.jpg'
import image4 from '../../assets/images/products/scarf.jpg'
import image5 from '../../assets/images/products/leather jacket.jpg'
import image6 from '../../assets/images/products/Casual Shirt.jpg'
import image7 from '../../assets/images/products/baseball cap.jpg'
import image8 from '../../assets/images/products/shirt.jpg'
import image9 from '../../assets/images/products/yoga pants.jpg'
import image10 from '../../assets/images/products/backpack.jpg'
import image11 from '../../assets/images/products/sunglasses.jpg'
import image12 from '../../assets/images/products/perfume.jpg'


// headCells.js
export const headCells = [
  {
    id: "info", // this id should be same as the key of the object in tableData.js
    numeric: false,
    disablePadding: true,
    label: "PRODUCT INFO",
  },
  {
    id: "imageURL", 
    numeric: false,
    disablePadding: true, 
  },
  {
    id: "brand",
    numeric: true,
    disablePadding: false,
    label: "BRAND",
  },
  {
    id: "category",
    numeric: false,
    disablePadding: false,
    label: "Category",
  },
  {
    id: "size",
    numeric: true,
    disablePadding: false,
    label: "SIZE",
  },
  {
    id: "color",
    numeric: false,
    disablePadding: false,
     label: "COLOR",
  },
  {
    id: "quantity",
    numeric: true,
    disablePadding: false,
    label: "QUANTITY",
  },
  {
    id: "price",
    numeric: true,
    disablePadding: false,
    label: "PRICE (Rs.)",
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "STATUS",
  },
  // {
  //   id: "payment",
  //   numeric: false,
  //   disablePadding: false,
  //   label: "PAYMENT",
  // },
  {
    id: "actions",
    numeric: false,
    disablePadding: false,
    label: "ACTIONS",
  },
];

export const additionalFields = [
  {
    id: "description",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "subcategory",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "gender",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "fitType",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "discount",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "availability",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "material",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "care",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "material",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "occasion",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "season",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "ageGroup",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "xsq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "sq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "mq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "lq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "mq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "lq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "xlq",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "Q28",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "Q30",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "Q32",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "Q34",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "Q36",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "size7",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "size8",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "size9",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "size10",
    numeric: false,
    disablePadding: false,
  },
  {
    id: "size11",
    numeric: false,
    disablePadding: false,
  },
  
];

// these are filter box options
export const filterOptions = [
  {
    id:'category', // this id should be same as the id in headCells.js
    label: "Category",
    options: ["Clothing", "Accessories", "Footwear"],
  },
  {
    id:'color',
    label: "Color",
    options: ["Black", "Grey", "Blue", "Brown","Green", "White", "Undefined"],
  },
  {
    id:'status',
    label: "Status",
    options: ["Active", "Disable"],
  },
  // {
  //   id:'payment',
  //   label: "Payment",
  //   options: ["Paid", "Unpaid"],
  // },
  
];


// tableData.js
export const tableData = [
  {
    id: 1,
    info: "Casual T-Shirts",
    orderId: "081794MT",
    brand: "Bear Appeal",
    category: "Clothing",
    subcategory: "Tops",
    size: "S,M,L,XL",
    color: "White, Green, Yellow",
    gender: 'Woman',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 59,
    xsq: 0,
    sq:20,
    mq:20,
    lq:10,
    xlq:9,
    fitType: "Regular Fit",
    material: "Cotton",
    pattern: "Solid",
    care: "Machine wash",
    price: 2000,
    discount: "10%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image1,
},
{
    id: 2,
    info: "Slim Fit Jeans",
    orderId: "081794MT",
    brand: "Levi's",
    category: "Clothing",
    subcategory: "Bottom",
    size: "28,30,32,34,36",
    color: "Blue, Black",
    gender: 'Woman',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 45,
    Q28:5,
    Q30:10,
    Q32:10,
    Q34:10,
    Q36:10,
    fitType: "Slim Fit",
    material: "Denim",
    pattern: "Solid",
    care: "Machine wash",
    price: 4000,
    discount: "15%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image2,
},
{
    id: 3,
    info: "Running Shoes",
    orderId: "081794MT",
    brand: "Nike",
    category: "Footwear",
    subcategory: "Shoes",
    size: "7,8,9,10,11",
    color: "Undefined",
    gender: 'Unisex',
    ageGroup: "Adult",
    occasion: "Sports",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 30,
    size7:5,
    size8:10,
    size9:5,
    size10:5,
    size11:5,
    fitType: "Regular Fit",
    material: "Synthetic",
    pattern: "Solid",
    care: "Wipe with clean cloth",
    price: 11000,
    discount: "20%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image3,
},
{
    id: 4,
    info: "Woolen Scarf",
    orderId: "081794MT",
    brand: "Cashmere",
    category: "Accessories",
    subcategory: "Scarves",
    size: "One Size",
    color: "Brown, Grey",
    gender: 'Woman',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "Winter",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 75,
    fitType: "Regular Fit",
    material: "Wool",
    pattern: "Solid",
    care: "Dry clean only",
    price: 3500,
    discount: "5%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image4,
},
{
    id: 5,
    info: "Leather Jacket",
    orderId: "081794MT",
    brand: "AllSaints",
    category: "Clothing",
    subcategory: "Outer Wear",
    size: "S,M,L,XL",
    color: "Black, Beige",
    gender: 'Woman',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "Winter",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 20,
    xsq: 0,
    sq:7,
    mq:5,
    lq:4,
    xlq:4,
    fitType: "Regular Fit",
    material: "Leather",
    pattern: "Solid",
    care: "Specialist clean",
    price: 8320,
    discount: "10%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image5,
},
{
    id: 6,
    info: "Casual Shirt",
    orderId: "081794MT",
    brand: "Tommy Hilfiger",
    category: "Clothing",
    subcategory: "Tops",
    size: "XS,S,M,L,XL",
    color: "Black, White, Blue",
    gender: 'Men',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 60,
    xsq: 10,
    sq:10,
    mq:20,
    lq:10,
    xlq:10,
    fitType: "Regular Fit",
    material: "Cotton",
    pattern: "Checked",
    care: "Machine wash",
    price: 3250,
    discount: "15%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image6,
},
{
    id: 7,
    info: "Baseball Cap",
    orderId: "081794MT",
    brand: "Sporty Gear",
    category: "Accessories",
    subcategory: "Hats",
    size: "One Size",
    color: "Undefined",
    gender: 'Unisex',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "Summer",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 90,
    fitType: "Regular Fit",
    material: "Cotton",
    pattern: "Solid",
    care: "Hand wash",
    price: 1750,
    discount: "10%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image7,
},
{
    id: 8,
    info: "Formal Shirt",
    orderId: "081794MT",
    brand: "SWX",
    category: "Clothing",
    subcategory: "Tops",
    size: "XS,S,M,L,XL",
    color: "White, Light-Green",
    gender: 'Men',
    ageGroup: "Adult",
    occasion: "Formal",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 50,
    xsq: 10,
    sq:10,
    mq:10,
    lq:10,
    xlq:10,
    fitType: "Slim Fit",
    material: "Cotton",
    pattern: "Solid",
    care: "Machine wash",
    price: 3000,
    discount: "15%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image8,
},
{
    id: 9,
    info: "Yoga Pants",
    orderId: "081794MT",
    brand: "Lululemon",
    category: "Clothing",
    subcategory: "Active Wear",
    size: "S,M,L",
    color: "Green, Grey, Purple",
    gender: 'Woman',
    ageGroup: "Adult",
    occasion: "Sports",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 25,
    xsq: 0,
    sq: 10,
    mq: 5,
    lq: 10,
    xlq: 0,
    fitType: "Slim Fit",
    material: "Spandex",
    pattern: "Solid",
    care: "Machine wash",
    price: 5000,
    discount: "10%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image9,
},
{
    id: 10,
    info: "Backpack",
    orderId: "081794MT",
    brand: "Jansport",
    category: "Accessories",
    subcategory: "Bag",
    size: "One Size",
    color: "Blue, Pink, Teal",
    gender: 'Unisex',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 40,
    fitType: "Regular Fit",
    material: "Polyester",
    pattern: "Solid",
    care: "Wipe with clean cloth",
    price: 6500,
    discount: "15%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image10,
},
{
    id: 11,
    info: "Sunglasses",
    orderId: "081794MT",
    brand: "Lenskart",
    category: "Accessories",
    subcategory: "Glasses",
    size: "One Size",
    color: "Black",
    gender: 'Unisex',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 60,
    fitType: "Regular Fit",
    material: "Plastic",
    pattern: "Solid",
    care: "Wipe with clean cloth",
    price: 2500,
    discount: "10%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image11,
},
{
    id: 12,
    info: "Perfume",
    orderId: "081794MT",
    brand: "Givenchy",
    category: "Accessories",
    subcategory: "Fragrance",
    size: "One Size",
    color: "Undefined",
    gender: 'Women',
    ageGroup: "Adult",
    occasion: "Casual",
    season: "All Seasons",
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    quantity: 60,
    fitType: "Regular Fit",
    material: "Liquid",
    pattern: "N/A",
    care: "Store in a cool place",
    price: 2500,
    discount: "15%",
    availability: "In Stock",
    status: "Active",
    imageUrl: image12,
}

];

  